T: 3
split: 1
feature: videoclip
seed: 42
is_pad: 1
training:
  batch_size: 256
  epochs: 200
  lr: 0.0001
  weight_decay: 0.00001
model:
  model_n: attention
  num_layers: 1
  num_heads: 1
loss:
  ce_w: 1.0
  mse_w: 0.2